import { Translations, Part } from './types';

export const TRANSLATIONS: Translations = {
  en: {
    searchPlaceholder: "Search by MPN, Keyword, or Manufacturer...",
    heroTitle: "Global Semiconductor Supply Chain",
    heroSubtitle: "Procure electronic components with industrial-grade precision and speed.",
    searchButton: "Search Inventory",
    uploadBom: "Upload BOM",
    inStock: "In Stock",
    obsolete: "Obsolete",
    leadTime: "Lead Time",
    lowStock: "Low Stock",
    price: "Price",
    qty: "Qty",
    mfr: "Mfr",
    desc: "Description",
    datasheet: "Datasheet",
    addToCart: "Add",
    requestQuote: "Request Quote",
    filter: "Filter",
    navProducts: "Products",
    navManufacturers: "Manufacturers",
    navSolutions: "Solutions",
    navResources: "Resources",
    aiSummary: "AI Summary",
    techSpecs: "Tech Specs",
    footerCopyright: "© 2024 ChipStore Inc. All rights reserved.",
    region: "Region",
    startSourcing: "Start Sourcing",
    viewAll: "View All Products",
    fastShipping: "Global Logistics",
    fastShippingDesc: "Same-day shipping to 180+ countries via DHL/FedEx.",
    qualityCert: "ISO 9001 Certified",
    qualityCertDesc: "Anti-counterfeit lab testing on all high-value components.",
    qualityInspect: "Quality Inspection",
    qualityInspectDesc: "Every chip undergoes strict visual and electrical testing before shipment.",
    bomModalTitle: "Batch Quotation (BOM)",
    bomDropzone: "Drag & drop your Excel/CSV file here",
    bomBrowse: "or browse files",
    submitBom: "Submit BOM",
    name: "Full Name",
    email: "Business Email",
    rfq: "RFQ",
    // New Search Page Keys
    home: "Home",
    breadcrumbsSearch: "Search",
    filtersHeader: "Filters",
    manufacturer: "Manufacturer",
    availability: "Availability",
    package: "Package",
    allPackages: "All Packages",
    resultsFor: "Results for",
    allProducts: "All Products",
    showingProducts: "products available for immediate dispatch",
    relevance: "Relevance",
    colImg: "Img",
    colMpn: "MPN / Manufacturer",
    colDesc: "Description",
    colStock: "Stock",
    colPrice: "Price (USD)",
    colAction: "Action",
    clearFilters: "Clear all filters",
    noResults: "No parts found matching your criteria.",
    showing: "Showing",
    of: "of"
  },
  cn: {
    searchPlaceholder: "按 MPN、关键字或制造商搜索...",
    heroTitle: "全球半导体供应链",
    heroSubtitle: "以工业级精度和速度采购电子元件。",
    searchButton: "搜索库存",
    uploadBom: "上传 BOM",
    inStock: "有现货",
    obsolete: "已停产",
    leadTime: "订货",
    lowStock: "库存紧张",
    price: "价格",
    qty: "数量",
    mfr: "制造商",
    desc: "描述",
    datasheet: "数据手册",
    addToCart: "添加",
    requestQuote: "请求报价",
    filter: "筛选",
    navProducts: "产品",
    navManufacturers: "制造商",
    navSolutions: "解决方案",
    navResources: "资源",
    aiSummary: "AI 摘要",
    techSpecs: "技术规格",
    footerCopyright: "© 2024 ChipStore Inc. 版权所有。",
    region: "地区",
    startSourcing: "开始采购",
    viewAll: "查看所有产品",
    fastShipping: "全球物流",
    fastShippingDesc: "通过 DHL/FedEx 当天发货至 180 多个国家。",
    qualityCert: "ISO 9001 认证",
    qualityCertDesc: "所有高价值组件均经过防伪实验室测试。",
    qualityInspect: "质量检测",
    qualityInspectDesc: "每个芯片在发货前都经过严格的视觉和电气测试。",
    bomModalTitle: "批量报价 (BOM)",
    bomDropzone: "将您的 Excel/CSV 文件拖放到此处",
    bomBrowse: "或浏览文件",
    submitBom: "提交 BOM",
    name: "全名",
    email: "企业邮箱",
    rfq: "询价",
    // New Search Page Keys
    home: "首页",
    breadcrumbsSearch: "搜索",
    filtersHeader: "筛选条件",
    manufacturer: "制造商",
    availability: "库存状态",
    package: "封装",
    allPackages: "所有封装",
    resultsFor: "搜索结果：",
    allProducts: "所有产品",
    showingProducts: "件产品可立即发货",
    relevance: "相关度",
    colImg: "图片",
    colMpn: "MPN / 制造商",
    colDesc: "描述",
    colStock: "库存",
    colPrice: "价格 (USD)",
    colAction: "操作",
    clearFilters: "清除所有筛选",
    noResults: "未找到符合条件的零件。",
    showing: "显示",
    of: "/"
  },
  es: {
    searchPlaceholder: "Buscar por MPN, palabra clave o fabricante...",
    heroTitle: "Cadena de Suministro Global",
    heroSubtitle: "Adquiera componentes electrónicos con precisión industrial.",
    searchButton: "Buscar Inventario",
    uploadBom: "Subir BOM",
    inStock: "En Stock",
    obsolete: "Obsoleto",
    leadTime: "Bajo Pedido",
    lowStock: "Stock Bajo",
    price: "Precio",
    qty: "Cant",
    mfr: "Fab",
    desc: "Descripción",
    datasheet: "Ficha Técnica",
    addToCart: "Añadir",
    requestQuote: "Presupuesto",
    filter: "Filtrar",
    navProducts: "Productos",
    navManufacturers: "Fabricantes",
    navSolutions: "Soluciones",
    navResources: "Recursos",
    aiSummary: "Resumen IA",
    techSpecs: "Especificaciones",
    footerCopyright: "© 2024 ChipStore Inc. Todos los derechos reservados.",
    region: "Región",
    startSourcing: "Empezar",
    viewAll: "Ver Productos",
    fastShipping: "Logística Global",
    fastShippingDesc: "Envío el mismo día a más de 180 países.",
    qualityCert: "Certificado ISO 9001",
    qualityCertDesc: "Pruebas de laboratorio anti-falsificación.",
    qualityInspect: "Inspección de Calidad",
    qualityInspectDesc: "Cada chip se somete a pruebas visuales y eléctricas estrictas.",
    bomModalTitle: "Cotización por Lotes (BOM)",
    bomDropzone: "Arrastre y suelte su archivo Excel/CSV aquí",
    bomBrowse: "o examinar archivos",
    submitBom: "Enviar BOM",
    name: "Nombre Completo",
    email: "Correo Corporativo",
    rfq: "Consultar",
    // New Search Page Keys
    home: "Inicio",
    breadcrumbsSearch: "Búsqueda",
    filtersHeader: "Filtros",
    manufacturer: "Fabricante",
    availability: "Disponibilidad",
    package: "Paquete",
    allPackages: "Todos los paquetes",
    resultsFor: "Resultados para",
    allProducts: "Todos los productos",
    showingProducts: "productos disponibles para envío inmediato",
    relevance: "Relevancia",
    colImg: "Img",
    colMpn: "MPN / Fabricante",
    colDesc: "Descripción",
    colStock: "Stock",
    colPrice: "Precio (USD)",
    colAction: "Acción",
    clearFilters: "Borrar filtros",
    noResults: "No se encontraron piezas.",
    showing: "Mostrando",
    of: "de"
  },
  de: {
    searchPlaceholder: "Nach MPN, Stichwort oder Hersteller suchen...",
    heroTitle: "Globale Halbleiter-Lieferkette",
    heroSubtitle: "Beschaffen Sie elektronische Komponenten mit Präzision.",
    searchButton: "Suchen",
    uploadBom: "BOM hochladen",
    inStock: "Auf Lager",
    obsolete: "Veraltet",
    leadTime: "Lieferzeit",
    lowStock: "Geringer Bestand",
    price: "Preis",
    qty: "Menge",
    mfr: "Herst",
    desc: "Beschreibung",
    datasheet: "Datenblatt",
    addToCart: "Kaufen",
    requestQuote: "Anfrage",
    filter: "Filter",
    navProducts: "Produkte",
    navManufacturers: "Hersteller",
    navSolutions: "Lösungen",
    navResources: "Ressourcen",
    aiSummary: "KI-Zusammenfassung",
    techSpecs: "Technische Daten",
    footerCopyright: "© 2024 ChipStore Inc. Alle Rechte vorbehalten.",
    region: "Region",
    startSourcing: "Beschaffung starten",
    viewAll: "Alle Produkte",
    fastShipping: "Globale Logistik",
    fastShippingDesc: "Versand am selben Tag in über 180 Länder.",
    qualityCert: "ISO 9001 Zertifiziert",
    qualityCertDesc: "Fälschungssichere Labortests.",
    qualityInspect: "Qualitätsprüfung",
    qualityInspectDesc: "Jeder Chip wird vor dem Versand strengen Tests unterzogen.",
    bomModalTitle: "BOM Hochladen",
    bomDropzone: "Excel/CSV-Datei hier ablegen",
    bomBrowse: "oder Dateien durchsuchen",
    submitBom: "BOM Senden",
    name: "Vollständiger Name",
    email: "Geschäfts-E-Mail",
    rfq: "Anfrage",
    // New Search Page Keys
    home: "Startseite",
    breadcrumbsSearch: "Suche",
    filtersHeader: "Filter",
    manufacturer: "Hersteller",
    availability: "Verfügbarkeit",
    package: "Gehäuse",
    allPackages: "Alle Gehäuse",
    resultsFor: "Ergebnisse für",
    allProducts: "Alle Produkte",
    showingProducts: "Produkte sofort verfügbar",
    relevance: "Relevanz",
    colImg: "Bild",
    colMpn: "MPN / Hersteller",
    colDesc: "Beschreibung",
    colStock: "Bestand",
    colPrice: "Preis (USD)",
    colAction: "Aktion",
    clearFilters: "Filter löschen",
    noResults: "Keine Teile gefunden.",
    showing: "Zeige",
    of: "von"
  }
};

export const MOCK_PARTS: Part[] = [
  {
    id: '1',
    mpn: 'STM32F407VGT6',
    manufacturer: 'STMicroelectronics',
    description: 'MCU 32-bit ARM Cortex-M4 RISC 1MB Flash 3.3V 100-Pin LQFP',
    category: 'Integrated Circuits (ICs)',
    stock: 2450,
    price: 8.45,
    pricingTiers: [{minQty: 1, price: 8.45}, {minQty: 100, price: 7.90}, {minQty: 1000, price: 7.15}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '2',
    mpn: 'LM358DR',
    manufacturer: 'Texas Instruments',
    description: 'Dual Operational Amplifier, 3V to 32V Supply, 8-SOIC',
    category: 'Linear - Amplifiers',
    stock: 15000,
    price: 0.12,
    pricingTiers: [{minQty: 1, price: 0.12}, {minQty: 2500, price: 0.08}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '3',
    mpn: 'CC2540F256RHAR',
    manufacturer: 'Texas Instruments',
    description: 'RF SoC Bluetooth Low Energy 2.4GHz 256kB Flash 40-Pin VQFN',
    category: 'RF/IF and RFID',
    stock: 0,
    price: 0,
    currency: 'USD',
    status: 'Lead Time',
    rohs: true,
  },
  {
    id: '4',
    mpn: 'ATMEGA328P-PU',
    manufacturer: 'Microchip',
    description: 'MCU 8-bit AVR RISC 32KB Flash 1.8V/2.5V/3.3V/5V 28-Pin PDIP',
    category: 'Embedded - Microcontrollers',
    stock: 430,
    price: 2.15,
    pricingTiers: [{minQty: 1, price: 2.15}],
    currency: 'USD',
    status: 'Low Stock',
    rohs: true,
  },
  {
    id: '5',
    mpn: 'XC7Z020-1CLG400C',
    manufacturer: 'AMD Xilinx',
    description: 'SoC Zynq-7000 Artix-7 FPGA+Dual ARM Cortex-A9 400-Pin CSBGA',
    category: 'Embedded - System On Chip (SoC)',
    stock: 0,
    price: 0,
    currency: 'USD',
    status: 'Obsolete',
    rohs: false,
  },
  {
    id: '6',
    mpn: 'IRFZ44N',
    manufacturer: 'Infineon',
    description: 'MOSFET N-CH 55V 49A TO-220AB Power MOSFET',
    category: 'Discrete Semiconductor Products',
    stock: 8900,
    price: 0.85,
    pricingTiers: [{minQty: 1, price: 0.85}, {minQty: 50, price: 0.75}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '7',
    mpn: 'ESP32-WROOM-32E',
    manufacturer: 'Espressif Systems',
    description: 'WiFi/BT/BLE MCU Module 4MB SPI Flash PCB Antenna',
    category: 'RF/IF and RFID',
    stock: 1200,
    price: 3.50,
    pricingTiers: [{minQty: 1, price: 3.50}, {minQty: 100, price: 2.95}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '8',
    mpn: 'STM32H743ZIT6',
    manufacturer: 'STMicroelectronics',
    description: 'High-performance MCU ARM Cortex-M7 400MHz 2MB Flash',
    category: 'Integrated Circuits (ICs)',
    stock: 560,
    price: 14.50,
    pricingTiers: [{minQty: 1, price: 14.50}, {minQty: 100, price: 13.20}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '9',
    mpn: 'TMS320F28335PGFA',
    manufacturer: 'Texas Instruments',
    description: 'Digital Signal Controller (DSC), 150MHz, 176-LQFP',
    category: 'Embedded - DSP',
    stock: 85,
    price: 18.75,
    pricingTiers: [{minQty: 1, price: 18.75}],
    currency: 'USD',
    status: 'Low Stock',
    rohs: true,
  },
  {
    id: '10',
    mpn: 'TPS5430DDAR',
    manufacturer: 'Texas Instruments',
    description: 'IC REG BUCK ADJ 3A 8SOPWRPAD',
    category: 'PMIC - Voltage Regulators',
    stock: 12500,
    price: 2.10,
    pricingTiers: [{minQty: 1, price: 2.10}, {minQty: 1000, price: 1.85}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '11',
    mpn: 'ATMEGA2560-16AU',
    manufacturer: 'Microchip',
    description: 'IC MCU 8BIT 256KB FLASH 100TQFP',
    category: 'Embedded - Microcontrollers',
    stock: 3200,
    price: 8.90,
    pricingTiers: [{minQty: 1, price: 8.90}, {minQty: 100, price: 8.10}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '12',
    mpn: 'LM317T',
    manufacturer: 'STMicroelectronics',
    description: 'IC REG LIN POS ADJ 1.5A TO220AB',
    category: 'PMIC - Voltage Regulators',
    stock: 50000,
    price: 0.25,
    pricingTiers: [{minQty: 1, price: 0.25}, {minQty: 1000, price: 0.18}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '13',
    mpn: 'MAX232CSE+',
    manufacturer: 'Analog Devices',
    description: 'IC TRANSCEIVER FULL 2/2 16SOIC',
    category: 'Interface - Drivers',
    stock: 0,
    price: 0,
    currency: 'USD',
    status: 'Lead Time',
    rohs: true,
  },
  {
    id: '14',
    mpn: 'NE555DR',
    manufacturer: 'Texas Instruments',
    description: 'IC OSC SINGLE TIMER 100KHZ 8-SOIC',
    category: 'Clock/Timing',
    stock: 22000,
    price: 0.15,
    pricingTiers: [{minQty: 1, price: 0.15}, {minQty: 2500, price: 0.11}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  },
  {
    id: '15',
    mpn: 'PIC16F877A-I/P',
    manufacturer: 'Microchip',
    description: 'IC MCU 8BIT 14KB FLASH 40DIP',
    category: 'Embedded - Microcontrollers',
    stock: 850,
    price: 4.50,
    pricingTiers: [{minQty: 1, price: 4.50}, {minQty: 100, price: 4.10}],
    currency: 'USD',
    status: 'In Stock',
    rohs: true,
  }
];